# Generated by Django 3.0.8 on 2020-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('climate', models.CharField(max_length=50)),
                ('terrain', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('producers', models.CharField(max_length=200)),
                ('planets', models.ManyToManyField(related_name='movies', to='characters.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=10)),
                ('movies', models.ManyToManyField(related_name='characters', to='characters.Movie')),
            ],
        ),
    ]
